### ISSUE TITLE
Fix un-rounded elements

### ISSUE THREAD

**Issue by pugson** [dubstrike/twitter-dark-mode#42]
![img](http://share.wojtek.im/1eyqnQ+)

**Comment by Pandawan** [comment]
I added some CSS to fix that, here's the code that I used:
```css
.tweet-form.condensed * .btn {
	background-color: transparent !important;
	border-color: transparent !important;
}
```

I have more things that fix other small problems that I found, [here's a gist for it](https://gist.github.com/PandawanFr/e7c8bd8a5e4c0614fe25444bb28e93c5).
