### ISSUE TITLE
Little white flecks around the corners of floating conversations

### ISSUE THREAD

**Issue by joeysino** [dubstrike/twitter-dark-mode#97]
When I view a tweets like this one, there is a tiny white fleck in the top-left and top-right corners of the floating div.

https://twitter.com/dan_abramov/status/909396104537616384

I fixed it in TamperMonkey by overriding these rules:

```css
.DMActivity--open, .permalink-container{
  border-radius: 8px;
}
.PermalinkOverlay .permalink{
  border-radius: 12px;
}
```
